version: '3.9'


services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: loteria
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql


  backend: 
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    depends_on:
      - db